service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
functions:
  graphql:
    handler: src/graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
		cors: true
package:
  exclude:
    - .env
    - apollo.config.js
plugins:
  - serverless-offline